/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Device service. Represents a row in the &quot;device&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mobilekipyonetim.service.model.impl.DeviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mobilekipyonetim.service.model.impl.DeviceImpl}.
 * </p>
 *
 * @author 002834
 * @see Device
 * @see com.mobilekipyonetim.service.model.impl.DeviceImpl
 * @see com.mobilekipyonetim.service.model.impl.DeviceModelImpl
 * @generated
 */
public interface DeviceModel extends BaseModel<Device>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device model instance should use the {@link Device} interface instead.
	 */

	/**
	 * Returns the primary key of this device.
	 *
	 * @return the primary key of this device
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this device.
	 *
	 * @param primaryKey the primary key of this device
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the entity ID of this device.
	 *
	 * @return the entity ID of this device
	 */
	public int getEntityId();

	/**
	 * Sets the entity ID of this device.
	 *
	 * @param entityId the entity ID of this device
	 */
	public void setEntityId(int entityId);

	/**
	 * Returns the group ID of this device.
	 *
	 * @return the group ID of this device
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this device.
	 *
	 * @param groupId the group ID of this device
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this device.
	 *
	 * @return the company ID of this device
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this device.
	 *
	 * @param companyId the company ID of this device
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this device.
	 *
	 * @return the user ID of this device
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this device.
	 *
	 * @param userId the user ID of this device
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this device.
	 *
	 * @return the user uuid of this device
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this device.
	 *
	 * @param userUuid the user uuid of this device
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this device.
	 *
	 * @return the user name of this device
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this device.
	 *
	 * @param userName the user name of this device
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this device.
	 *
	 * @return the create date of this device
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this device.
	 *
	 * @param createDate the create date of this device
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this device.
	 *
	 * @return the modified date of this device
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this device.
	 *
	 * @param modifiedDate the modified date of this device
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the msisdn of this device.
	 *
	 * @return the msisdn of this device
	 */
	@AutoEscape
	public String getMsisdn();

	/**
	 * Sets the msisdn of this device.
	 *
	 * @param msisdn the msisdn of this device
	 */
	public void setMsisdn(String msisdn);

	/**
	 * Returns the imei of this device.
	 *
	 * @return the imei of this device
	 */
	@AutoEscape
	public String getImei();

	/**
	 * Sets the imei of this device.
	 *
	 * @param imei the imei of this device
	 */
	public void setImei(String imei);

	/**
	 * Returns the reg ID of this device.
	 *
	 * @return the reg ID of this device
	 */
	@AutoEscape
	public String getRegId();

	/**
	 * Sets the reg ID of this device.
	 *
	 * @param regId the reg ID of this device
	 */
	public void setRegId(String regId);

	/**
	 * Returns the organization ID of this device.
	 *
	 * @return the organization ID of this device
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this device.
	 *
	 * @param organizationId the organization ID of this device
	 */
	public void setOrganizationId(long organizationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Device device);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Device> toCacheModel();

	@Override
	public Device toEscapedModel();

	@Override
	public Device toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}