/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OrderPriority service. Represents a row in the &quot;OrderPriority&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mobilekipyonetim.service.model.impl.OrderPriorityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mobilekipyonetim.service.model.impl.OrderPriorityImpl}.
 * </p>
 *
 * @author 002834
 * @see OrderPriority
 * @see com.mobilekipyonetim.service.model.impl.OrderPriorityImpl
 * @see com.mobilekipyonetim.service.model.impl.OrderPriorityModelImpl
 * @generated
 */
public interface OrderPriorityModel extends BaseModel<OrderPriority>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order priority model instance should use the {@link OrderPriority} interface instead.
	 */

	/**
	 * Returns the primary key of this order priority.
	 *
	 * @return the primary key of this order priority
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this order priority.
	 *
	 * @param primaryKey the primary key of this order priority
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the order priority entity ID of this order priority.
	 *
	 * @return the order priority entity ID of this order priority
	 */
	public int getOrderPriorityEntityId();

	/**
	 * Sets the order priority entity ID of this order priority.
	 *
	 * @param orderPriorityEntityId the order priority entity ID of this order priority
	 */
	public void setOrderPriorityEntityId(int orderPriorityEntityId);

	/**
	 * Returns the group ID of this order priority.
	 *
	 * @return the group ID of this order priority
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this order priority.
	 *
	 * @param groupId the group ID of this order priority
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this order priority.
	 *
	 * @return the company ID of this order priority
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this order priority.
	 *
	 * @param companyId the company ID of this order priority
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this order priority.
	 *
	 * @return the user ID of this order priority
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this order priority.
	 *
	 * @param userId the user ID of this order priority
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this order priority.
	 *
	 * @return the user uuid of this order priority
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this order priority.
	 *
	 * @param userUuid the user uuid of this order priority
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this order priority.
	 *
	 * @return the user name of this order priority
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this order priority.
	 *
	 * @param userName the user name of this order priority
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this order priority.
	 *
	 * @return the create date of this order priority
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this order priority.
	 *
	 * @param createDate the create date of this order priority
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this order priority.
	 *
	 * @return the modified date of this order priority
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this order priority.
	 *
	 * @param modifiedDate the modified date of this order priority
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this order priority.
	 *
	 * @return the organization ID of this order priority
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this order priority.
	 *
	 * @param organizationId the organization ID of this order priority
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the description of this order priority.
	 *
	 * @return the description of this order priority
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this order priority.
	 *
	 * @param description the description of this order priority
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OrderPriority orderPriority);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OrderPriority> toCacheModel();

	@Override
	public OrderPriority toEscapedModel();

	@Override
	public OrderPriority toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}