/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Poi service. Represents a row in the &quot;Poi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mobilekipyonetim.service.model.impl.PoiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mobilekipyonetim.service.model.impl.PoiImpl}.
 * </p>
 *
 * @author 002834
 * @see Poi
 * @see com.mobilekipyonetim.service.model.impl.PoiImpl
 * @see com.mobilekipyonetim.service.model.impl.PoiModelImpl
 * @generated
 */
public interface PoiModel extends BaseModel<Poi>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a poi model instance should use the {@link Poi} interface instead.
	 */

	/**
	 * Returns the primary key of this poi.
	 *
	 * @return the primary key of this poi
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this poi.
	 *
	 * @param primaryKey the primary key of this poi
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the poi entity ID of this poi.
	 *
	 * @return the poi entity ID of this poi
	 */
	public int getPoiEntityId();

	/**
	 * Sets the poi entity ID of this poi.
	 *
	 * @param poiEntityId the poi entity ID of this poi
	 */
	public void setPoiEntityId(int poiEntityId);

	/**
	 * Returns the group ID of this poi.
	 *
	 * @return the group ID of this poi
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this poi.
	 *
	 * @param groupId the group ID of this poi
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this poi.
	 *
	 * @return the company ID of this poi
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this poi.
	 *
	 * @param companyId the company ID of this poi
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this poi.
	 *
	 * @return the user ID of this poi
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this poi.
	 *
	 * @param userId the user ID of this poi
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this poi.
	 *
	 * @return the user uuid of this poi
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this poi.
	 *
	 * @param userUuid the user uuid of this poi
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this poi.
	 *
	 * @return the user name of this poi
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this poi.
	 *
	 * @param userName the user name of this poi
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this poi.
	 *
	 * @return the create date of this poi
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this poi.
	 *
	 * @param createDate the create date of this poi
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this poi.
	 *
	 * @return the modified date of this poi
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this poi.
	 *
	 * @param modifiedDate the modified date of this poi
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization ID of this poi.
	 *
	 * @return the organization ID of this poi
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this poi.
	 *
	 * @param organizationId the organization ID of this poi
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the name of this poi.
	 *
	 * @return the name of this poi
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this poi.
	 *
	 * @param name the name of this poi
	 */
	public void setName(String name);

	/**
	 * Returns the lat of this poi.
	 *
	 * @return the lat of this poi
	 */
	@AutoEscape
	public String getLat();

	/**
	 * Sets the lat of this poi.
	 *
	 * @param lat the lat of this poi
	 */
	public void setLat(String lat);

	/**
	 * Returns the lng of this poi.
	 *
	 * @return the lng of this poi
	 */
	@AutoEscape
	public String getLng();

	/**
	 * Sets the lng of this poi.
	 *
	 * @param lng the lng of this poi
	 */
	public void setLng(String lng);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Poi poi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Poi> toCacheModel();

	@Override
	public Poi toEscapedModel();

	@Override
	public Poi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}