/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Vehicle service. Represents a row in the &quot;Vehicle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mobilekipyonetim.service.model.impl.VehicleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mobilekipyonetim.service.model.impl.VehicleImpl}.
 * </p>
 *
 * @author 002834
 * @see Vehicle
 * @see com.mobilekipyonetim.service.model.impl.VehicleImpl
 * @see com.mobilekipyonetim.service.model.impl.VehicleModelImpl
 * @generated
 */
public interface VehicleModel extends BaseModel<Vehicle>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vehicle model instance should use the {@link Vehicle} interface instead.
	 */

	/**
	 * Returns the primary key of this vehicle.
	 *
	 * @return the primary key of this vehicle
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this vehicle.
	 *
	 * @param primaryKey the primary key of this vehicle
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the vehicle entity ID of this vehicle.
	 *
	 * @return the vehicle entity ID of this vehicle
	 */
	public int getVehicleEntityId();

	/**
	 * Sets the vehicle entity ID of this vehicle.
	 *
	 * @param vehicleEntityId the vehicle entity ID of this vehicle
	 */
	public void setVehicleEntityId(int vehicleEntityId);

	/**
	 * Returns the group ID of this vehicle.
	 *
	 * @return the group ID of this vehicle
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vehicle.
	 *
	 * @param groupId the group ID of this vehicle
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vehicle.
	 *
	 * @return the company ID of this vehicle
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vehicle.
	 *
	 * @param companyId the company ID of this vehicle
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vehicle.
	 *
	 * @return the user ID of this vehicle
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vehicle.
	 *
	 * @param userId the user ID of this vehicle
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vehicle.
	 *
	 * @return the user uuid of this vehicle
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this vehicle.
	 *
	 * @param userUuid the user uuid of this vehicle
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vehicle.
	 *
	 * @return the user name of this vehicle
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vehicle.
	 *
	 * @param userName the user name of this vehicle
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vehicle.
	 *
	 * @return the create date of this vehicle
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vehicle.
	 *
	 * @param createDate the create date of this vehicle
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vehicle.
	 *
	 * @return the modified date of this vehicle
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vehicle.
	 *
	 * @param modifiedDate the modified date of this vehicle
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plate of this vehicle.
	 *
	 * @return the plate of this vehicle
	 */
	@AutoEscape
	public String getPlate();

	/**
	 * Sets the plate of this vehicle.
	 *
	 * @param plate the plate of this vehicle
	 */
	public void setPlate(String plate);

	/**
	 * Returns the organization ID of this vehicle.
	 *
	 * @return the organization ID of this vehicle
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this vehicle.
	 *
	 * @param organizationId the organization ID of this vehicle
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the device ID of this vehicle.
	 *
	 * @return the device ID of this vehicle
	 */
	public long getDeviceId();

	/**
	 * Sets the device ID of this vehicle.
	 *
	 * @param deviceId the device ID of this vehicle
	 */
	public void setDeviceId(long deviceId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Vehicle vehicle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Vehicle> toCacheModel();

	@Override
	public Vehicle toEscapedModel();

	@Override
	public Vehicle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}