/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.mobilekipyonetim.service.model.OrderPriority;
import com.mobilekipyonetim.service.model.OrderPriorityModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the OrderPriority service. Represents a row in the &quot;OrderPriority&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.mobilekipyonetim.service.model.OrderPriorityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrderPriorityImpl}.
 * </p>
 *
 * @author 002834
 * @see OrderPriorityImpl
 * @see com.mobilekipyonetim.service.model.OrderPriority
 * @see com.mobilekipyonetim.service.model.OrderPriorityModel
 * @generated
 */
public class OrderPriorityModelImpl extends BaseModelImpl<OrderPriority>
	implements OrderPriorityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a order priority model instance should use the {@link com.mobilekipyonetim.service.model.OrderPriority} interface instead.
	 */
	public static final String TABLE_NAME = "OrderPriority";
	public static final Object[][] TABLE_COLUMNS = {
			{ "orderPriorityEntityId", Types.INTEGER },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "organizationId", Types.BIGINT },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table OrderPriority (orderPriorityEntityId INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,organizationId LONG,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OrderPriority";
	public static final String ORDER_BY_JPQL = " ORDER BY orderPriority.orderPriorityEntityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OrderPriority.orderPriorityEntityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.mobilekipyonetim.service.model.OrderPriority"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.mobilekipyonetim.service.model.OrderPriority"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.mobilekipyonetim.service.model.OrderPriority"));

	public OrderPriorityModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _orderPriorityEntityId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setOrderPriorityEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orderPriorityEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OrderPriority.class;
	}

	@Override
	public String getModelClassName() {
		return OrderPriority.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("orderPriorityEntityId", getOrderPriorityEntityId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer orderPriorityEntityId = (Integer)attributes.get(
				"orderPriorityEntityId");

		if (orderPriorityEntityId != null) {
			setOrderPriorityEntityId(orderPriorityEntityId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@Override
	public int getOrderPriorityEntityId() {
		return _orderPriorityEntityId;
	}

	@Override
	public void setOrderPriorityEntityId(int orderPriorityEntityId) {
		_orderPriorityEntityId = orderPriorityEntityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_organizationId = organizationId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public OrderPriority toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OrderPriority)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OrderPriorityImpl orderPriorityImpl = new OrderPriorityImpl();

		orderPriorityImpl.setOrderPriorityEntityId(getOrderPriorityEntityId());
		orderPriorityImpl.setGroupId(getGroupId());
		orderPriorityImpl.setCompanyId(getCompanyId());
		orderPriorityImpl.setUserId(getUserId());
		orderPriorityImpl.setUserName(getUserName());
		orderPriorityImpl.setCreateDate(getCreateDate());
		orderPriorityImpl.setModifiedDate(getModifiedDate());
		orderPriorityImpl.setOrganizationId(getOrganizationId());
		orderPriorityImpl.setDescription(getDescription());

		orderPriorityImpl.resetOriginalValues();

		return orderPriorityImpl;
	}

	@Override
	public int compareTo(OrderPriority orderPriority) {
		int primaryKey = orderPriority.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OrderPriority)) {
			return false;
		}

		OrderPriority orderPriority = (OrderPriority)obj;

		int primaryKey = orderPriority.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OrderPriority> toCacheModel() {
		OrderPriorityCacheModel orderPriorityCacheModel = new OrderPriorityCacheModel();

		orderPriorityCacheModel.orderPriorityEntityId = getOrderPriorityEntityId();

		orderPriorityCacheModel.groupId = getGroupId();

		orderPriorityCacheModel.companyId = getCompanyId();

		orderPriorityCacheModel.userId = getUserId();

		orderPriorityCacheModel.userName = getUserName();

		String userName = orderPriorityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			orderPriorityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			orderPriorityCacheModel.createDate = createDate.getTime();
		}
		else {
			orderPriorityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			orderPriorityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			orderPriorityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		orderPriorityCacheModel.organizationId = getOrganizationId();

		orderPriorityCacheModel.description = getDescription();

		String description = orderPriorityCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			orderPriorityCacheModel.description = null;
		}

		return orderPriorityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{orderPriorityEntityId=");
		sb.append(getOrderPriorityEntityId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.mobilekipyonetim.service.model.OrderPriority");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>orderPriorityEntityId</column-name><column-value><![CDATA[");
		sb.append(getOrderPriorityEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OrderPriority.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			OrderPriority.class
		};
	private int _orderPriorityEntityId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _organizationId;
	private String _description;
	private OrderPriority _escapedModel;
}