/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mobilekipyonetim.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.mobilekipyonetim.service.model.Poi;
import com.mobilekipyonetim.service.model.PoiModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Poi service. Represents a row in the &quot;Poi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.mobilekipyonetim.service.model.PoiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PoiImpl}.
 * </p>
 *
 * @author 002834
 * @see PoiImpl
 * @see com.mobilekipyonetim.service.model.Poi
 * @see com.mobilekipyonetim.service.model.PoiModel
 * @generated
 */
public class PoiModelImpl extends BaseModelImpl<Poi> implements PoiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a poi model instance should use the {@link com.mobilekipyonetim.service.model.Poi} interface instead.
	 */
	public static final String TABLE_NAME = "Poi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "poiEntityId", Types.INTEGER },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "organizationId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "lat", Types.VARCHAR },
			{ "lng", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Poi (poiEntityId INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,organizationId LONG,name VARCHAR(75) null,lat VARCHAR(75) null,lng VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Poi";
	public static final String ORDER_BY_JPQL = " ORDER BY poi.poiEntityId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Poi.poiEntityId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.mobilekipyonetim.service.model.Poi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.mobilekipyonetim.service.model.Poi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.mobilekipyonetim.service.model.Poi"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long ORGANIZATIONID_COLUMN_BITMASK = 2L;
	public static long POIENTITYID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.mobilekipyonetim.service.model.Poi"));

	public PoiModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _poiEntityId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setPoiEntityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _poiEntityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Poi.class;
	}

	@Override
	public String getModelClassName() {
		return Poi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("poiEntityId", getPoiEntityId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("organizationId", getOrganizationId());
		attributes.put("name", getName());
		attributes.put("lat", getLat());
		attributes.put("lng", getLng());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer poiEntityId = (Integer)attributes.get("poiEntityId");

		if (poiEntityId != null) {
			setPoiEntityId(poiEntityId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long organizationId = (Long)attributes.get("organizationId");

		if (organizationId != null) {
			setOrganizationId(organizationId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String lat = (String)attributes.get("lat");

		if (lat != null) {
			setLat(lat);
		}

		String lng = (String)attributes.get("lng");

		if (lng != null) {
			setLng(lng);
		}
	}

	@Override
	public int getPoiEntityId() {
		return _poiEntityId;
	}

	@Override
	public void setPoiEntityId(int poiEntityId) {
		_poiEntityId = poiEntityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getLat() {
		if (_lat == null) {
			return StringPool.BLANK;
		}
		else {
			return _lat;
		}
	}

	@Override
	public void setLat(String lat) {
		_lat = lat;
	}

	@Override
	public String getLng() {
		if (_lng == null) {
			return StringPool.BLANK;
		}
		else {
			return _lng;
		}
	}

	@Override
	public void setLng(String lng) {
		_lng = lng;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Poi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Poi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PoiImpl poiImpl = new PoiImpl();

		poiImpl.setPoiEntityId(getPoiEntityId());
		poiImpl.setGroupId(getGroupId());
		poiImpl.setCompanyId(getCompanyId());
		poiImpl.setUserId(getUserId());
		poiImpl.setUserName(getUserName());
		poiImpl.setCreateDate(getCreateDate());
		poiImpl.setModifiedDate(getModifiedDate());
		poiImpl.setOrganizationId(getOrganizationId());
		poiImpl.setName(getName());
		poiImpl.setLat(getLat());
		poiImpl.setLng(getLng());

		poiImpl.resetOriginalValues();

		return poiImpl;
	}

	@Override
	public int compareTo(Poi poi) {
		int primaryKey = poi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Poi)) {
			return false;
		}

		Poi poi = (Poi)obj;

		int primaryKey = poi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PoiModelImpl poiModelImpl = this;

		poiModelImpl._originalOrganizationId = poiModelImpl._organizationId;

		poiModelImpl._setOriginalOrganizationId = false;

		poiModelImpl._originalName = poiModelImpl._name;

		poiModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Poi> toCacheModel() {
		PoiCacheModel poiCacheModel = new PoiCacheModel();

		poiCacheModel.poiEntityId = getPoiEntityId();

		poiCacheModel.groupId = getGroupId();

		poiCacheModel.companyId = getCompanyId();

		poiCacheModel.userId = getUserId();

		poiCacheModel.userName = getUserName();

		String userName = poiCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			poiCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			poiCacheModel.createDate = createDate.getTime();
		}
		else {
			poiCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			poiCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			poiCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		poiCacheModel.organizationId = getOrganizationId();

		poiCacheModel.name = getName();

		String name = poiCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			poiCacheModel.name = null;
		}

		poiCacheModel.lat = getLat();

		String lat = poiCacheModel.lat;

		if ((lat != null) && (lat.length() == 0)) {
			poiCacheModel.lat = null;
		}

		poiCacheModel.lng = getLng();

		String lng = poiCacheModel.lng;

		if ((lng != null) && (lng.length() == 0)) {
			poiCacheModel.lng = null;
		}

		return poiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{poiEntityId=");
		sb.append(getPoiEntityId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", organizationId=");
		sb.append(getOrganizationId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", lat=");
		sb.append(getLat());
		sb.append(", lng=");
		sb.append(getLng());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.mobilekipyonetim.service.model.Poi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>poiEntityId</column-name><column-value><![CDATA[");
		sb.append(getPoiEntityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationId</column-name><column-value><![CDATA[");
		sb.append(getOrganizationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lat</column-name><column-value><![CDATA[");
		sb.append(getLat());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lng</column-name><column-value><![CDATA[");
		sb.append(getLng());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Poi.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Poi.class };
	private int _poiEntityId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private String _name;
	private String _originalName;
	private String _lat;
	private String _lng;
	private long _columnBitmask;
	private Poi _escapedModel;
}